### ISSUE TITLE
Increment on click

### ISSUE THREAD

**Issue by SuciuCalin** [SuciuCalin/js_clicker#2]
![increment on click](https://user-images.githubusercontent.com/27139870/65816261-2c25d680-e202-11e9-8b66-02fc778b5bba.gif)

Pasii de urmat in Javascript ar fi:
- O variabila care sa stocheze valoarea
- Un selector pt elementul HTML in care vrei sa fie afisata valoarea
- O functie care sa creasca valoarea cu 1 si sa o puna in elementul de HTML

Javascript DOM elements selectors:
- https://developer.mozilla.org/en-US/docs/Web/API/Document_object_model/Locating_DOM_elements_using_selectors
- https://www.w3schools.com/js/js_htmldom_elements.asp

Javascript Functions:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions
- https://www.w3schools.com/js/js_function_definition.asp

Introduction in Javascript:
- https://www.codecademy.com/learn/introduction-to-javascript

**Comment by Calinnn1** [comment]
Imi merge counterul doar cu ce am in HTML si daca sterg ce am in javascript. Adica am gasit formula care sa le lege pe ambele dar am observat ca am putut sterge tot ce am in javascript si tot ruleaza, nu ma prind.

**Comment by SuciuCalin** [comment]
> Imi merge counterul doar cu ce am in HTML si daca sterg ce am in javascript. Adica am gasit formula care sa le lege pe ambele dar am observat ca am putut sterge tot ce am in javascript si tot ruleaza, nu ma prind.

No problem. Urca pe GitHub ce ai facut local si fa un Pull Request. E mai usor asa daca e si codul.

Din "Git Bash" in folderul in care proiectul -> `git status` -> `git add .` -> `git commit -m "mesajul"` -> `git push origin master`. Apoi din pagina de GitHub unde e proiectul mergi in "Pull Request" -> "New Pull Request".

**Comment by Calinnn1** [comment]
Multumesc, a fost foarte de ajutor.
    On Tuesday, October 8, 2019, 12:01:55 PM GMT+3, Suciu Eugen-Calin <notifications@github.com> wrote:  
 
 

Imi merge counterul doar cu ce am in HTML si daca sterg ce am in javascript. Adica am gasit formula care sa le lege pe ambele dar am observat ca am putut sterge tot ce am in javascript si tot ruleaza, nu ma prind.


No problem. Urca pe GitHub ce ai facut local si fa un Pull Request. E mai usor asa daca e si codul.

Din "Git Bash" in folderul in care proiectul -> git status -> git add . -> git commit -m "mesajul" -> git push origin master. Apoi din pagina de GitHub unde e proiectul mergi in "Pull Request" -> "New Pull Request".

**Comment by SuciuCalin** [comment]
Closed with 8ebcda9d2164da5a8aca4f1bd3ff12ea082a437d
