### ISSUE TITLE
Activate buttons

### ISSUE THREAD

**Issue by SuciuCalin** [SuciuCalin/js_clicker#5]
![image](https://user-images.githubusercontent.com/27139870/66715661-71cfcb00-edce-11e9-9c04-b3f3b5a221dd.png)

Cand ajungi la o anumita valoare, de ex 20, se "activeaza" butonul "Increment Click Value":
 - Se schimba culoarea background-ului din gri in negru
 - Se schimba culoarea textului din negru in alb
Ideal: nu se poate da click pe butonul respectiv (sau daca dai click nu se intampla nimic) inainte sa fie "activ".

Acelasi lucru de mai sus, se intampla si cu butonul "Idle Click", in momentul in care ajungi la o alta valoare, de ex 50.

Resurse:
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/conditionals

Vei avea nevoie de cate o variabila care sa stocheze "costul" butonului (valoarea la care ar trebui sa devina activ). Apoi, folosind conditionals, verifici cand valoarea click-ului = costul butonului. Daca e true, devine activ.

**Comment by Calinnn1** [comment]
Nu stiu sa rezolv Activate buttons. Cand as putea sa vin sa ma ajuti?
